- name: Configure Search Head Cluster Secret
  ansible.builtin.ini_file:
    path: "{{ splunk_home }}/etc/system/local/server.conf"
    section: "shclustering"
    option: "pass4SymmKey"
    value: "{{ shcluster_secret }}"
    owner: splunk
    group: splunk
    mode: "0644"

- name: Restart Splunk
  command: >
    {{ splunk_home }}/bin/splunk
    restart