[cluster_manager]
cluster-manager.prod.kiranpanchavati.online

[indexers]
indexer1.prod.kiranpanchavati.online
indexer2.prod.kiranpanchavati.online

[search_heads]
search-head1.prod.kiranpanchavati.online
search-head2.prod.kiranpanchavati.online
search-head3.prod.kiranpanchavati.online

[deployer]
deployer.prod.kiranpanchavati.online

[deployment_server]
deployment-server.prod.kiranpanchavati.online

[license_manager]
license-master.prod.kiranpanchavati.online

[monitoring_console]
monitoring-console.prod.kiranpanchavati.online

[heavy_forwarders]
heavyforwarder.prod.kiranpanchavati.online