---
- name: Configure Cluster Manager
  command: >
    {{ splunk_home }}/bin/splunk
    edit cluster-config
    -mode manager
    -replication_factor {{ replication_factor }}
    -search_factor {{ search_factor }}
    -secret {{ cluster_secret }}
    -cluster_label {{ cluster_label }}
    -auth {{ splunk_admin_user }}:{{ splunk_admin_password }}

- name: Restart Splunk
  command: >
    {{ splunk_home }}/bin/splunk
    restart

- name: Wait for Splunk to start
  command: >
    {{ splunk_home }}/bin/splunk
    status
  register: status
  retries: 30
  delay: 10
  until: "'splunkd is running' in status.stdout"
  changed_when: false

- name: Display Splunk Status
  debug:
    var: status.stdout