---
- name: Check the status of the Heavy Forwarder
  ansible.builtin.command:
    cmd: >
      {{ splunk_home }}/bin/splunk status
  register: status
  changed_when: false
  failed_when: false

- name: Print Heavy Forwarder status
  ansible.builtin.debug:
    var: status.stdout_lines

- name: Connect Heavy Forwarder to Deployment Server
  ansible.builtin.command:
    cmd: >
      {{ splunk_home }}/bin/splunk set deploy-poll
      {{ deployment_server_uri }}
      -auth {{ splunk_admin_user }}:{{ splunk_admin_password }}
  register: deploy_server
  no_log: true

- name: Print Deployment Server result
  ansible.builtin.debug:
    var: deploy_server.stdout_lines

- name: Restart Heavy Forwarder
  ansible.builtin.command:
    cmd: >
      {{ splunk_home }}/bin/splunk restart
      -auth {{ splunk_admin_user }}:{{ splunk_admin_password }}
  register: restart

- name: Print restart result
  ansible.builtin.debug:
    var: restart.stdout_lines