---
- name: Check Heavy Forwarder status
  ansible.builtin.command:
    argv:
      - "{{ splunk_home }}/bin/splunk"
      - status
  become: true
  become_user: splunk
  register: splunk_status
  changed_when: false
  failed_when: false

- name: Print Heavy Forwarder status
  ansible.builtin.debug:
    var: splunk_status.stdout_lines

- name: Connect Heavy Forwarder to Deployment Server
  ansible.builtin.command:
    argv:
      - "{{ splunk_home }}/bin/splunk"
      - set
      - deploy-poll
      - "{{ deployment_server_uri }}"
      - -auth
      - "{{ splunk_admin_user }}:{{ splunk_admin_password }}"
  become: true
  become_user: splunk
  register: deployment_server_result
  changed_when: deployment_server_result.rc == 0
  no_log: true
  notify: Restart Splunk

- name: Connect Heavy Forwarder to License Manager
  ansible.builtin.command:
    argv:
      - "{{ splunk_home }}/bin/splunk"
      - edit
      - licenser-localpeer
      - -manager_uri
      - "https://{{ license_manager_uri }}"
      - -auth
      - "{{ splunk_admin_user }}:{{ splunk_admin_password }}"
  become: true
  become_user: splunk
  register: license_manager_result
  changed_when: license_manager_result.rc == 0
  no_log: true
  when: use_remote_license_manager | default(false) | bool
  notify: Restart Splunk