- name: Create serverclass.conf file
  ansible.builtin.copy:
    dest: "{{ splunk_home }}/etc/system/local/serverclass.conf"
    owner: splunk
    group: splunk
    mode: '0644'
    content: |
      [serverClass:dev_infrateam_linux]
      whitelist.0 = *

      [serverClass:dev_infrateam_linux:app:deployment_server]
      restartSplunkd = true
  notify: Restart Splunk