- name: Create a Splunk local directory if not available
  ansible.builtin.file:
    path: "{{ splunk_home }}/etc/system/local/serverclass.conf"
    state: directory 
    owner: splunk
    group: splunk
    mode: '0755'

- name: Create a serverclass.conf file
  ansible.builtin.file:
    path: "{{ splunk_home }}/etc/system/local/serverclass.conf"
    state: directory
    content: |
      [serverclass:deployment_server]
      serverclass = dev_infrateam_linux
      owner = splunk
      group = splunk
      mode = '0755'
  notify: Restart Splunk